
import React, { useState } from 'react';
import { 
  XMarkIcon, 
  MapPinIcon, 
  ClockIcon, 
  ShieldCheckIcon, 
  ArrowRightCircleIcon,
  ChevronLeftIcon,
  DocumentTextIcon,
  /* Added DocumentArrowDownIcon to imports */
  DocumentArrowDownIcon
} from '@heroicons/react/24/outline';
import { ClassInfo } from '../types';
import { jsPDF } from 'https://esm.sh/jspdf';

interface ReportWizardProps {
  data: ClassInfo;
  confidence: number;
  sourceImage: string;
  onCancel: () => void;
}

export const ReportWizard: React.FC<ReportWizardProps> = ({ data, confidence, sourceImage, onCancel }) => {
  const [includeLocation, setIncludeLocation] = useState(true);
  const [includeDetails, setIncludeDetails] = useState(true);
  const [renderSafe, setRenderSafe] = useState('');
  const [furtherActions, setFurtherActions] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [location, setLocation] = useState<{ lat: number; lon: number } | null>(null);

  // Fetch location if toggled
  React.useEffect(() => {
    if (includeLocation && !location) {
      navigator.geolocation.getCurrentPosition(
        (pos) => setLocation({ lat: pos.coords.latitude, lon: pos.coords.longitude }),
        (err) => console.error("Location error:", err),
        { enableHighAccuracy: true }
      );
    }
  }, [includeLocation]);

  const generatePDF = async () => {
    setIsGenerating(true);
    try {
      const doc = new jsPDF();
      const margin = 20;
      let y = margin;

      // Header
      doc.setFillColor(30, 41, 59); // Slate-800
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text("EXPLODEX ORDNANCE REPORT", margin, 25);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text("Automated Offline Classification Summary", margin, 32);

      y = 55;
      doc.setTextColor(30, 41, 59);
      
      // Finding Section
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text("1. CLASSIFICATION FINDINGS", margin, y);
      y += 8;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.text(`Ordnance Type: ${data.title}`, margin, y);
      y += 6;
      doc.text(`Confidence Level: ${(confidence * 100).toFixed(2)}%`, margin, y);
      y += 6;
      doc.text(`Timestamp: ${new Date().toLocaleString()}`, margin, y);
      
      if (includeLocation && location) {
        y += 6;
        doc.text(`Position: ${location.lat.toFixed(6)}, ${location.lon.toFixed(6)}`, margin, y);
      }

      // Image Section
      y += 15;
      doc.setFont('helvetica', 'bold');
      doc.text("2. VISUAL EVIDENCE", margin, y);
      y += 5;
      try {
        // Simple heuristic to fit image
        doc.addImage(sourceImage, 'JPEG', margin, y, 80, 60);
        y += 70;
      } catch (e) {
        doc.text("[Image could not be rendered]", margin, y + 10);
        y += 20;
      }

      // Operational Notes
      doc.setFont('helvetica', 'bold');
      doc.text("3. OPERATIONAL NOTES", margin, y);
      y += 8;
      
      doc.setFontSize(10);
      doc.text("Render-Safe Procedure Followed:", margin, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      const rsLines = doc.splitTextToSize(renderSafe || "None documented.", 170);
      doc.text(rsLines, margin, y);
      y += (rsLines.length * 5) + 5;

      doc.setFont('helvetica', 'bold');
      doc.text("Further Actions Required:", margin, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      const faLines = doc.splitTextToSize(furtherActions || "None documented.", 170);
      doc.text(faLines, margin, y);
      y += (faLines.length * 5) + 15;

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Explodex Offline AI. This document is provided for informational purposes.", 105, 285, { align: 'center' });

      // Save
      const filename = `Explodex_Report_${data.title.replace(/\s+/g, '_')}_${Date.now()}.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error("PDF Generation failed:", err);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="flex flex-col h-full animate-in slide-in-from-right-8 duration-300">
      {/* Wizard Header */}
      <div className="p-6 border-b border-white/5 bg-slate-900/40 flex items-center justify-between shrink-0">
        <div className="flex items-center gap-3">
          <button onClick={onCancel} className="p-1 hover:bg-white/10 rounded-full transition-colors text-slate-400">
            <ChevronLeftIcon className="w-6 h-6" />
          </button>
          <div>
            <h2 className="text-xl font-bold text-white leading-tight">Report Wizard</h2>
            <p className="text-xs text-slate-500 font-mono">Step: Document Finalization</p>
          </div>
        </div>
        <div className="flex items-center gap-2 px-3 py-1 bg-primary/10 border border-primary/20 rounded-full">
          <DocumentTextIcon className="w-4 h-4 text-primary" />
          <span className="text-[10px] font-bold text-primary uppercase tracking-widest">Drafting</span>
        </div>
      </div>

      <div className="flex-grow overflow-y-auto p-8 space-y-8">
        {/* Toggles */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div 
            onClick={() => setIncludeLocation(!includeLocation)}
            className={`p-4 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${includeLocation ? 'bg-primary/5 border-primary/40 shadow-sm' : 'bg-slate-800/50 border-white/5 hover:border-white/10'}`}
          >
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-lg ${includeLocation ? 'bg-primary/20 text-primary' : 'bg-slate-700 text-slate-400'}`}>
                <MapPinIcon className="w-5 h-5" />
              </div>
              <div className="text-left">
                <span className="block text-sm font-bold text-white">Position & Time</span>
                <span className="text-[10px] text-slate-500 uppercase">GPS Metadata</span>
              </div>
            </div>
            <div className={`w-10 h-5 rounded-full relative transition-colors ${includeLocation ? 'bg-primary' : 'bg-slate-700'}`}>
              <div className={`absolute top-1 w-3 h-3 bg-white rounded-full transition-all ${includeLocation ? 'left-6' : 'left-1'}`} />
            </div>
          </div>

          <div 
            onClick={() => setIncludeDetails(!includeDetails)}
            className={`p-4 rounded-xl border transition-all cursor-pointer flex items-center justify-between ${includeDetails ? 'bg-secondary/5 border-secondary/40 shadow-sm' : 'bg-slate-800/50 border-white/5 hover:border-white/10'}`}
          >
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-lg ${includeDetails ? 'bg-secondary/20 text-secondary' : 'bg-slate-700 text-slate-400'}`}>
                <ShieldCheckIcon className="w-5 h-5" />
              </div>
              <div className="text-left">
                <span className="block text-sm font-bold text-white">Class Details</span>
                <span className="text-[10px] text-slate-500 uppercase">Description & Tags</span>
              </div>
            </div>
            <div className={`w-10 h-5 rounded-full relative transition-colors ${includeDetails ? 'bg-secondary' : 'bg-slate-700'}`}>
              <div className={`absolute top-1 w-3 h-3 bg-white rounded-full transition-all ${includeDetails ? 'left-6' : 'left-1'}`} />
            </div>
          </div>
        </div>

        {/* Narrative Input */}
        <div className="space-y-6">
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
              <ShieldCheckIcon className="w-4 h-4" />
              Render-safe procedure followed
            </label>
            <textarea 
              value={renderSafe}
              onChange={(e) => setRenderSafe(e.target.value)}
              placeholder="Detail the steps taken to neutralize or safe the item..."
              className="w-full bg-slate-900/50 border border-white/10 rounded-xl p-4 text-sm text-slate-200 focus:border-primary focus:ring-1 focus:ring-primary outline-none min-h-[100px] transition-all"
            />
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-widest flex items-center gap-2">
              <ArrowRightCircleIcon className="w-4 h-4" />
              Further actions required
            </label>
            <textarea 
              value={furtherActions}
              onChange={(e) => setFurtherActions(e.target.value)}
              placeholder="e.g., EOD disposal scheduled, area cordoned, local authorities notified..."
              className="w-full bg-slate-900/50 border border-white/10 rounded-xl p-4 text-sm text-slate-200 focus:border-primary focus:ring-1 focus:ring-primary outline-none min-h-[100px] transition-all"
            />
          </div>
        </div>
      </div>

      {/* Wizard Footer */}
      <div className="p-6 border-t border-white/5 bg-slate-900/80 shrink-0">
        <button
          onClick={generatePDF}
          disabled={isGenerating}
          className={`
            w-full py-4 px-6 rounded-xl font-bold text-lg shadow-lg flex items-center justify-center gap-3 transition-all
            ${isGenerating 
              ? 'bg-slate-700 text-slate-500 cursor-not-allowed' 
              : 'bg-gradient-to-r from-primary to-secondary text-white hover:shadow-primary/30 active:scale-[0.98]'}
          `}
        >
          {isGenerating ? (
            <div className="animate-spin rounded-full h-5 w-5 border-t-2 border-white" />
          ) : (
            <>
              <DocumentArrowDownIcon className="w-6 h-6" />
              Generate Final Report
            </>
          )}
        </button>
      </div>
    </div>
  );
};
